# -*- coding: utf-8 -*-
"""Codigo Graficas PHYPHOX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-993N4O6BAaGP7fV7pq49m5zb_nHoRp
"""

import pandas as pd
import matplotlib.pyplot as plt

try:
    df = pd.read_csv('Data.csv', sep='[,\t]', engine='python')

    fig, axs = plt.subplots(2, 1, figsize=(10, 12))

    axs[0].plot(df.iloc[:, 0], df.iloc[:, 1])
    axs[0].set_xlabel(df.columns[0])
    axs[0].set_ylabel(df.columns[1])
    axs[0].set_title('Velocidad Angular vs. Tiempo')


    axs[1].plot(df.iloc[:, 0], df.iloc[:, 2])
    axs[1].set_xlabel(df.columns[0])
    axs[1].set_ylabel(df.columns[2])
    axs[1].set_title('Aceleración vs. Tiempo')


    plt.tight_layout()
    plt.show()

except FileNotFoundError:
    print("Error: El archivo 'Data.csv' no fue encontrado.")
    print("Por favor, asegúrate de que el archivo está en el directorio correcto y el nombre es correcto.")
except Exception as e:
    print(f"Ocurrió un error: {e}")

import pandas as pd
import matplotlib.pyplot as plt

try:

    df_aceleracion = pd.read_csv('Raw Data.csv', sep='[,\t]', engine='python')


    fig, axs = plt.subplots(4, 1, figsize=(10, 24))

    axs[0].plot(df_aceleracion.iloc[:, 0], df_aceleracion.iloc[:, 1])
    axs[0].set_xlabel('Tiempo (s)')
    axs[0].set_ylabel('Aceleración en X')
    axs[0].set_title('Aceleración en el eje X vs. Tiempo')

    axs[1].plot(df_aceleracion.iloc[:, 0], df_aceleracion.iloc[:, 2])
    axs[1].set_xlabel('Tiempo (s)')
    axs[1].set_ylabel('Aceleración en Y')
    axs[1].set_title('Aceleración en el eje Y vs. Tiempo')


    axs[2].plot(df_aceleracion.iloc[:, 0], df_aceleracion.iloc[:, 3])
    axs[2].set_xlabel('Tiempo (s)')
    axs[2].set_ylabel('Aceleración en Z')
    axs[2].set_title('Aceleración en el eje Z vs. Tiempo')

    axs[3].plot(df_aceleracion.iloc[:, 0], df_aceleracion.iloc[:, 4])
    axs[3].set_xlabel('Tiempo (s)')
    axs[3].set_ylabel('Aceleración Absoluta')
    axs[3].set_title('Aceleración Absoluta vs. Tiempo')

    plt.tight_layout()
    plt.show()

except FileNotFoundError:
    print("Error: El archivo 'Raw Data.csv' no fue encontrado.")
    print("Por favor, asegúrate de que el archivo está en el directorio correcto y el nombre es correcto.")
except IndexError:
    print("Error: El archivo no tiene suficientes columnas para graficar las aceleraciones en x, y, y z.")
    print("Por favor, verifica el formato de tu archivo CSV.")
except Exception as e:
    print(f"Ocurrió un error: {e}")